### ISSUE TITLE
Invalid Literal With PCAP file

### ISSUE THREAD

**Issue by dmayall** [idaholab/NAVV#61]
# 🐛 Summary #

What's wrong? Please be specific.
II use the navv launch and put a pcap file into the pcap option and hit the process button and it runs for a few seconds then in the terminal states a invalid interal for int with base10. 
## To reproduce ##

1. Do this
launch navv 
2. Then this
put pcap file into pcap section
## Expected behavior ##

What did you expect to happen that didn't?
the excel sheet
## Any helpful log output or screenshots ##

Paste the results here:

```console
Traceback (most recent call last):
  File "C:\Users\dmayall\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmayall\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmayall\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmayall\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmayall\network-architecture-verification-and-validation\src\navv\gui\app.py", line 78, in download
    memfile = generate(
              ^^^^^^^^^
  File "C:\Users\dmayall\network-architecture-verification-and-validation\src\navv\gui\bll.py", line 55, in generate
    services, conn_states = get_package_data()
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmayall\network-architecture-verification-and-validation\src\navv\spreadsheet_tools.py", line 126, in get_package_data
    services, conn_states = pickle.load(f)
                            ^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '0L\r\n'
INFO:werkzeug:127.0.0.1 - - [08/Feb/2024 10:24:17] "POST /download HTTP/1.1" 500 -
```

Add any screenshots of the problem here.

**Comment by dmayall** [comment]
Forgot to add that I have tried multiple files in case of a file error.

**Comment by Dbones202** [comment]
What version were you running when this occured?

**Comment by Dbones202** [comment]
> Forgot to add that I have tried multiple files in case of a file error.
What version were you running?

**Comment by Dbones202** [comment]
Unable to reproduce error
