### ISSUE TITLE
Problem download updated spreadsheet file

### ISSUE THREAD

**Issue by syrinxtech** [idaholab/NAVV#70]
# 🐛 Summary #

What's wrong? Please be specific.
I captured PCAP data using tcpdump.  Then I ran zeek via cmd line to read PCAP data, and created the Excel spreadsheet.  I updated the spreadsheet to add the segment tab CIDR and color info.  When I run navv again and try to update the spreadsheet the download process craps out.
## To reproduce ##

1. Do this
2. source venv/bin/activate
1. Then this
2. navv launch

## Expected behavior ##

What did you expect to happen that didn't?
I expected navv to update the spreadsheet after I added the CIDR range and colored it.

## Any helpful log output or screenshots ##
zeek version 7.0.0
navv, version 3.3
Linux OT 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Paste the results here:

```console
ERROR:navv.gui.app:Exception on /download [POST]
Traceback (most recent call last):
  File "/home/bryan/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bryan/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bryan/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bryan/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bryan/venv/lib/python3.12/site-packages/navv/gui/app.py", line 78, in download
    memfile = generate(
              ^^^^^^^^^
  File "/home/bryan/venv/lib/python3.12/site-packages/navv/gui/bll.py", line 114, in generate
    start = float(forward[0])
                  ~~~~~~~^^^
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [02/Sep/2024 17:11:01] "POST /download HTTP/1.1" 500 -
```

Add any screenshots of the problem here.

**Comment by syrinxtech** [comment]
I also noticed that about 95% of the time when I first type "navv launch", the first attempt to start Firefox fails and I have to retry.  The first retry almost always works.

**Comment by Dbones202** [comment]
Unable to replicate the issue at this time.
